### PR TITLE
Prevent memory leaks by freeing ngspice command log

### PR DESCRIPTION
**Pull request by ARF1**
ngspice keeps an internal log of all commands executed. This leads to a memory leak when a large number of commands are sent.

This PR fixes this by periodically deleting the ngspice command log as recommended by the ngspice user manual.

### CODE REVIEW

**Comment by benedictjones** [comment]
Tried adding in these few lines of code to see if it would fix issue #246 (https://github.com/FabriceSalvaire/PySpice/issues/246). To test I lowered the limit from 10000 to 100. When it was triggered to free the memory, the code just crashed?

Copying the whole Shared.py file showed me that your file has added dependencies, is this what caused the problem?

**Comment by benedictjones** [comment]
I had hoped this would solve Issue #246 as such I tested this fix. Lowering the if statement threshold from 10000 to 100 (to more quickly see its effect) I found that when triggered it just causes python to crash?

(Using Windows Anaconda: python 3.8.5, pyspice 1.4.3)

**Comment by ARF1** [comment]
@benedictjones I cannot reproduce your crash and I suspect you made a mistake transposing my patch to your local installation.

That said, I believe that #246 is not a manifestation of this issue. You cannot produce a perceptible memory leak by just storing a hundred strings. The problem this PR fixes only comes into play when you execute several millions of commands without restart.

It sounds more like you are forgetting to call [`destroy()`](https://pyspice.fabrice-salvaire.fr/releases/v1.3/api/PySpice/Spice/NgSpice/Shared.html#PySpice.Spice.NgSpice.Shared.NgSpiceShared.destroy) after you have run a simulation. Ngspice keeps all data with a simulation in memory unless you tell it with `destroy()` that you definitely do not need it any longer. If you simulate in a loop you should probably have a `destroy()` in the loop as well.

If your simulation produce a significant amount of data it is very easy to fill your memory by running just a few of them without deleting your previous results.

**Comment by FabriceSalvaire** [comment]
Thanks.

**Pull request merged**
