### PR TITLE
Fix ngspice download URL

### PR DESCRIPTION
**Pull request by endolith**
ngspice directory structure changed from

https://sourceforge.net/projects/ngspice/files/ng-spice-rework/32/ngspice-32_dll_64.zip

to

https://sourceforge.net/projects/ngspice/files/ng-spice-rework/old-releases/32/ngspice-32_dll_64.zip

Try old-releases folder if main folder fails for a given version.

Raise a visible exception if 404 or other HTTP error to help identify
future problems.

### CODE REVIEW

**Comment by endolith** [comment]
This also fixes the Travis Windows build which was producing error

`OSError: cannot load library 'c:\python38\lib\site-packages\PySpice\Spice\NgSpice\Spice64_dll\dll-vs\ngspice.dll`

**Review by mister-scott — CHANGES_REQUESTED** [review]
Missing resolution for NGSPICE_MANUAL_URL, which suffers from same problem.

Additionally, this would be a good place to add one more fix for when user specifies ngspice version <=31. In those versions, the DLL naming did not contain a version number. In lines 230-240 (223-234 before pull request), if downloaded DLL's name is already 'ngspice.dll', the unlink command causes the DLL to be deleted, and results in error. Replacing those lines with the code below adds a check to prevent deletion if the dll-vs subdirectory only contains 'ngspice.dll'.

```
if dll_path.joinpath(src).exists():
    if target.exists():
        target.unlink()
    try:
        target.symlink_to(src)
    except OSError:
        # OSError: symbolic link privilege not held
        # Windows: If User Account Control (UAC) is on, any user with the "Create Symbolic
        #   Links" privilege that is not in the Administrators group can simply create a
        #   symbolic link.  For users within the Administrators group and with UAC on, the user
        #   must "Run as Administrator".
        shutil.copy(target.parent.joinpath(src), target)
```

**Comment by endolith** [comment]
@mister-scott Can you add that change using the "Insert a suggestion" tool on the "Files changed" tab?  I think it will credit you then

**Comment by endolith** [comment]
Added that.  Linux still fails, I don't know why.  Works on my Linux machine.

**Comment by FabriceSalvaire** [comment]
thanks

**Pull request merged**
