### PR TITLE
Rename files to avoid non-ascii characters

### PR DESCRIPTION
**Pull request by stuarteberg**
This PR renames files to avoid non-ascii characters to avoid git's "precomposed unicode is not supported" error on Mac.

Any Mac user with a recent version of git will encounter the following error when they clone the `PySpice` repo and run `git status`:

```
fatal: iconv_open(UTF-8,UTF-8-MAC) failed, but needed:
    precomposed unicode is not supported.
    If you want to use decomposed unicode, run
    "git config core.precomposeunicode false"
```

I called `git config core.precomposeunicode false` as suggested by the error message, and the problem disappeared.  I guess all Mac users must do that when cloning PySpice.

What's the cause? Apparently [something weird can happen][1] when transferring files with non-ASCII names to/from the Mac filesystem.  The PySpice repo contains two files with a non-ascii character (é):

```
examples/fundamental-laws/m4/thévenin-norton-theorem.m4
examples/fundamental-laws/thévenin-norton-theorem.py
```

[1]: https://gitlab.cecs.anu.edu.au/comp8440/git/commit/76759c7dff53e8c84e975b88cb8245587c14c7ba

I am not knowledgeable on the subject of "precomposed" vs. "decomposed" unicode, but here are some possible solutions:

- Change those two file names
- Maybe there is some way to fix the repo without changing the file names.
- Add a warning to Mac users in the README

This PR just changes the file names.

### CODE REVIEW

**Comment by FabriceSalvaire** [comment]
No problem to rename theses files, but it looks like Git is buggy.  How was installed Git ? Found this issues: https://github.com/conda-forge/git-feedstock/issues/50

**Comment by stuarteberg** [comment]
Nice find.  Yes, I installed git with conda-forge, which means git is relying on their build of `libiconv`.  Perhaps the problem lies in that build.

>Another issue with renaming: we cannot easily change the history.

In my testing, only the current file name triggers the problem.  After renaming (or removing) the files, the error does not occur.

OK, this is not a "must have" change.  It would be convenient for conda users (until the git build is fixed), but is otherwise not crucial.

**Comment by FabriceSalvaire** [comment]
I will wait ... because unicode must/should be supported in 2020 !

Did you try this https://git-scm.com/download/mac ?

**Comment by FabriceSalvaire** [comment]
**diacritic is annoying for command line users** e.g. how to enter the character with a lambda keyboard

**Pull request merged**
